name: Build BABASITARAM Vault APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.2'
          build-root-directory: ./AndroidProject

      - name: Build with Gradle
        run: gradle assembleDebug --stacktrace --info
        working-directory: ./AndroidProject

      - name: Rename APK
        run: mv AndroidProject/app/build/outputs/apk/debug/app-debug.apk AndroidProject/app/build/outputs/apk/debug/BABASITARAM_Vault_v5.11_Build_${{ github.run_number }}.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BABASITARAM-Vault-APK-v5.11
          path: AndroidProject/app/build/outputs/apk/debug/BABASITARAM_Vault_v5.11_Build_${{ github.run_number }}.apk
